### ISSUE TITLE
Target changes to BETAFPV 900 TX when clicking SELECT under Network Devices

### ISSUE THREAD

**Issue by avsaase** [ExpressLRS/ExpressLRS-Configurator#104]
## Expected Behavior

Not really sure actually.

## Current Behavior

With the new DNS device detection, my RX (Happymodel EP1) shows up under Network Devices. When I click SELECT, the device category is changed to BETAFPV 900 MHZ and the target to BETAFPV 900 TX.

## Steps to Reproduce

1. Select Hapymodel EP1 RX target with previously configured home wifi SSID and password

2. Choose WIFI Flashing Method

3. RX shows up under Network Devices

4. Click SELECT and see that the target has changed

## Your Environment

- Operating System and version: Windows 10, Configurator version 1.2.1
- RX hardware: Happymodel EP1 running master from a few weeks ago

**Comment by justinlampley** [comment]
Can you still replicate the issue?  If so, can you post what is shown as the target of that device in the Network Devices list?

**Comment by avsaase** [comment]
Hmm, no, looks like I cannot reproduce the problem. The receiver is now running the master branch from yesterday and the target doesn't change when I click select. Strange.

**Comment by jurgelenas** [comment]
> Hmm, no, looks like I cannot reproduce the problem. The receiver is now running the master branch from yesterday and the target doesn't change when I click select. Strange.

Can you post application logs?

**Comment by avsaase** [comment]
Are the logs deleted when the configurator is closed? I have a log file but I don't see any dates or times so I don't know when it was recorded.

**Comment by jurgelenas** [comment]
> Are the logs deleted when the configurator is closed? I have a log file but I don't see any dates or times so I don't know when it was recorded.

Logs are persistent across application launches

**Comment by avsaase** [comment]
Here you go: [expressslrs-configurator.zip](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/7463626/expressslrs-configurator.zip). I changed my binding phrase and wifi password in the log.

**Comment by justinlampley** [comment]
Thanks!  You were on a version of the firmware that didn't populated the device target on the MDNS record, so the configurator didn't know which target to choose and the BETAFPV 900 TX is the first device in the array.  When the target can't be found in the list of available devices it should not select anything at all, so I will need to look at that.

Relevant part of the log:

{
  context: {
    type: 'DEVICE_ADDED',
    data: {
      name: 'elrs_rx_70039F1C944B',
      dns: 'elrs_rx.local',
      ip: '192.168.0.159',
      options: [],
      version: '',
      target: '',
      type: '',
      vendor: '',
      port: 80
    }
  },
  level: 'info',
  message: 'multicast dns device added'
}

**Comment by jurgelenas** [comment]
> Thanks! You were on a version of the firmware that didn't populated the device target on the MDNS record, so the configurator didn't know which target to choose and the BETAFPV 900 TX is the first device in the array. When the target can't be found in the list of available devices it should not select anything at all, so I will need to look at that.
> 
> Relevant part of the log: `{ context: { type: 'DEVICE_ADDED', data: { name: 'elrs_rx_70039F1C944B', dns: 'elrs_rx.local', ip: '192.168.0.159', options: [], version: '', target: '', type: '', vendor: '', port: 80 } }, level: 'info', message: 'multicast dns device added' }`

Any ideas how we could handle this case in the UI?

**Comment by justinlampley** [comment]
I am going to add in extra checks that handle the target empty situation as well as a check that ensures the MDNS target only matches to one device.  

Long explanation:

The StartsWith() function is used to match the MDNS target value to the list of known targets, since the MDNS target is the base target (TargetA) without the via portion at the end of the name (TargetA_via_UART), which is what we have in the configurator.  Since the MDNS target was blank, it matched to all targets and the first device match was chosen.  This could also be an issue if a target is created that starts the same as another target, TargetA and TargetA_V2 for instance, we may choose the wrong one since TargetA will match to both of them.  For now I am going to make sure the MDNS target only matches to one device, and if not, it won't select any device to avoid potentially selecting the wrong one.  We may need to look at adding the base target name to the device entry in devices.json so that we can do a straight match instead of using StartsWith, but this check will keep us from selecting the wrong device for the time being.
