### ISSUE TITLE
Warn users about binding phrases shorter than 8 characters in UserDefinesAdvisor

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#186]

**Comment by justinlampley** [comment]
I don't know that adding a warning if a binding phrase is less than 8 characters will be all that helpful, since it is not the length of the phrase that matters, but rather making sure it is unique.  Someone that was going to use 123456 will now just use 12345678.  What may be more helpful is to inform the user that they should not use common phrases or sequences like 000000 or 123456 because while the binding phrase is NOT a security feature, if someone you are flying with happens to use the same binding phrase, it could result in you interfering with each other.

**Comment by Tallestthomas** [comment]
I agree. I think the UX would be much better if there was better verbiage explaining why you should change the phrase to something unique, instead of just giving a hard non-consequential "must be this long" warning.

**Comment by jurgelenas** [comment]
Binding phrases shorter than 6 characters are already not accepted: https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/ddaf104fe03df8bf0ec75caa2b127a7b354c004f/src/ui/views/ConfiguratorView/UserDefinesValidator.ts#L42

I think this solution is sufficient. Closing the issue.
