### ISSUE TITLE
Allow flashing arbitrary file 

### ISSUE THREAD

**Issue by rickla** [ExpressLRS/ExpressLRS-Configurator#389]
Stuck in bricked/pass through mode, I want to flash the repartitioner image, but the configurator only allows elrs images.
Sorry if this feature exists but I can’t find it.

**Comment by justinlampley** [comment]
While that could be a useful feature to add, you do not need to flash the repartitioner image if you are flashing via any other method besides WIFI, since those other methods already do the repartitioning when it is flashing the new firmware.  The only flashing method that needs the repartitioner image is flashing via WIFI and you can just upload the repartitioner image when on the devices web page.
