### ISSUE TITLE
There are no 3.3.0 DIY 2.4GHz RX device targets in ELRS Configurator V1.6.0

### ISSUE THREAD

**Issue by BotSpace** [ExpressLRS/ExpressLRS-Configurator#559]
## Expected Behavior
I want to update the firmware on my DIY 2.4 GHz RX

## Current Behavior
There are no DIY 2.4 GHz RX device targets

## Steps to Reproduce
1. Download and install ExpressLRS Configurator V1.6.0
2. Select Releases -> 3.0.0
3. Select Device Category -> DIY 2.4 GHz
4. Select Device dropdown, there are no RX options available
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/47766188/e61a6a06-8009-45e8-af48-ea6a76f4c206)

## Possible Solution (Not obligatory)
I downgraded to 1.5.5, and the targets are there

## Context
just wanted to upgrade the firmware on my DIY 2.4GHz RX

## Your Environment
- Operating System and version: Windows 10, ELRS Configurator 1.6.0
- TX hardware: 3.0.0
- RX hardware: 3.3.0

**Comment by FireflySoul** [comment]
Same issue for DIY 900MHz receivers.

**Comment by pkendall64** [comment]
A lot of the DIY targets have moved to the "Generic" category as they are the base layout for a lot of manufactured devices.

**Comment by FireflySoul** [comment]
Thank you for replying!
I was not aware of the change you mentioned but seeing the ever growing number of Tx and Rx variants in the configurator I can see why it is necessary and my only suggestion would be to try to move all DYI targets to generic ones and remove the DIY category since it creates confusion.
If it would be possible, some kind of description or list of Rx/Tx compatible with the target selected in the configurator should help I think.

**Comment by nightflasher** [comment]
in the code i can still see the esp8285 + rfm95 RX targets, but the configurator 1.6.1 is missing those.
