### ISSUE TITLE
  I can't find this firmware Generic ESP8285 SX127x 900MHz RX  on the ExpressLRS Configurator ground station(1.6.1)

### ISSUE THREAD

**Issue by YangChen1234** [ExpressLRS/ExpressLRS-Configurator#609]
## Summary
  I can't find this firmware Generic ESP8285 SX127x 900MHz RX  on the ExpressLRS Configurator ground station(1.6.1)

I need firmware compiled for ESP8285 + sx1276 that can be downloaded from the ground station ExpressLRS Configurator ground station(1.6.1).

We used to have this firmware.
![7124a1fc053e66c4ba1f08606491ee4](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/89179705/7d3f793c-b6d5-4efb-a70e-563b23bc34c3)
But now I can't find it.

**Comment by pkendall64** [comment]
All the generic targets were removed from Configurator because some less reputable manufacturers were abusing the use of the generic targets. They are meant to be used as a basis for supported, tested and verified hardware.
i.e. if the target cannot be verified by the devs then it does not get a target.

**Comment by YangChen1234** [comment]
thank you

**Comment by Aricg** [comment]
It is very confusing to see my board as a target in the 2400-diy.json file in this repo, but having it not visible in the dropdown

I can see it was last visible in the 2.x branch of the ExpressLRS repo
```
[env:DIY_2400_RX_ESP8285_SX1280_via_WIFI]
```

However I can still build from source
```
❯ pio run -e DIY_2400_RX_ESP8285_SX1280_via_WIFI
***************************************
Obsolete PIO Core v6.1.16 is used (previous was 6.1.17)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/en/latest/core/installation/troubleshooting.html
***************************************
Processing DIY_2400_RX_ESP8285_SX1280_via_WIFI (platform: espressif8266@4.2.0; board: esp8285-8285; framework: arduino)
❯ ls .pio/build/DIY_2400_RX_ESP8285_SX1280_via_WIFI/
firmware.bin             ld      lib015  lib1c8  lib4a2  lib9ec  lib48d  lib96e  lib813  libbd9  libc50  libe83  libf43                        src
firmware.elf        

```

Perhaps a note about this in the U/I to the effect of
`if you dont see your device it's no longer supported but you can build from source`
would be helpful to future users.
cheers.

**Comment by jurgelenas** [comment]
@Aricg Unfortunately, the device you’re using was never officially supported by the project.

DIY targets were removed from the configurator because, in some cases (like yours), they were being used by certain manufacturers to bypass the normal target approval process.

The ExpressLRS project aims to ensure that all supported devices meet our best practices and safety guidelines. We’re always happy to work with manufacturers through our **free** partner program. It helps ensure their devices are properly validated and provide a reliable experience for users.

**Comment by Aricg** [comment]
understood, next purchase I'll make sure the board is in your dropdown. thanks.
