### ISSUE TITLE
ExpressLRS Configurator 1.7.1 crashes on BigSur

### ISSUE THREAD

**Issue by StoyanovVlad** [ExpressLRS/ExpressLRS-Configurator#633]
Here is a crashlog

[
[crashlog.txt](https://github.com/user-attachments/files/16182099/crashlog.txt)
](url)

**Comment by jurgelenas** [comment]
Most likely the support is not coming back since the BigSur is no longer supported by Apple itself. You can track the progress of this issue in #621.

In the meantime you can use 1.6.X ExpressLRS Configurator version or our web flasher when using google chrome: https://expresslrs.github.io/web-flasher/
